### ISSUE TITLE
It doesnt work properly on polygons that have interior

### ISSUE THREAD

**Issue by jacksparrow47** [bertt/triangulator#12]
Hi, I have a polygon that have a exterior and interior like bellow. 

`POLYGON Z((544618.2395 4406817.6168 792.125,544617.7368 4406820.5822 792.125, 544621.6316 4406821.2423 792.125, 544622.704 4406817.4021 792.125,544618.3995 4406816.6725 792.125, 544618.3899 4406816.7294 792.125, 544618.269 4406816.709 792.125,544618.314 4406816.4437 792.125, 544618.422 4406816.462 792.125, 544618.4061 4406816.5552 792.125,544622.7453 4406817.2908 792.125, 544623.4772 4406814.698 792.125, 544618.8538 4406813.9143 792.125,544618.5724 4406815.5746 792.125, 544618.4644 4406815.5563 792.125, 544618.7746 4406813.7264 792.125,544618.8719 4406813.7429 792.125, 544618.8595 4406813.816 792.125, 544622.6713 4406814.4621 792.125,544622.702 4406814.2806 792.125, 544622.8123 4406814.2992 792.125, 544623.0625 4406812.8231 792.125,544622.9523 4406812.8044 792.125, 544622.971 4406812.6938 792.125, 544623.0972 4406811.9495 792.125,544620.1356 4406811.4475 792.125, 544620.0094 4406812.1918 792.125, 544619.1592 4406812.0476 792.125,544619.0223 4406812.8556 792.125, 544618.925 4406812.8391 792.125, 544618.96 4406812.6327 792.125,544618.8488 4406812.6139 792.125, 544618.8676 4406812.5033 792.125, 544618.9994 4406812.5256 792.125,544619.0994 4406811.9355 792.125, 544619.231 4406811.9578 792.125, 544619.34 4406811.3148 792.125,544619.2084 4406811.2925 792.125, 544618.1294 4406811.1096 792.125, 544617.9204 4406812.3427 792.125,544617.9803 4406812.3529 792.125, 544617.9615 4406812.4635 792.125, 544617.8805 4406812.4498 792.125,544617.867 4406812.5295 792.125, 544617.8002 4406812.5182 792.125, 544617.6331 4406813.5041 792.125,544617.6999 4406813.5154 792.125, 544617.3412 4406815.6314 792.125, 544617.2335 4406815.6132 792.125,544617.2175 4406815.7077 792.125, 544617.1408 4406815.6947 792.125, 544617.1641 4406815.5575 792.125,544615.3418 4406815.2486 792.125, 544615.0238 4406817.1247 792.125, 544616.8461 4406817.4335 792.125,544616.9904 4406816.582 792.125, 544617.0671 4406816.595 792.125, 544616.9243 4406817.4373 792.125,544617.032 4406817.4556 792.125, 544617.1599 4406817.4773 792.125, 544617.1405 4406817.592 792.125,544615.0075 4406817.2305 792.125, 544614.5546 4406819.9028 792.125, 544617.6466 4406820.505 792.125,544618.1124 4406817.7568 792.125, 544618.0278 4406817.7424 792.125, 544618.0473 4406817.6277 792.125,544618.1115 4406817.6385 792.125, 544618.1186 4406817.5963 792.125, 544618.2395 4406817.6168 792.125),(544615.2738 4406815.1175 792.125, 544617.2816 4406815.4579 792.125, 544618.0584 4406810.8754 792.125,544624.4697 4406811.9622 792.125, 544624.4091 4406812.1752 792.125, 544623.2613 4406811.9806 792.125,544622.8434 4406814.4459 792.125, 544623.7214 4406814.5947 792.125, 544621.7643 4406821.4796 792.125,544614.4225 4406820.1398 792.125, 544615.2738 4406815.1175 792.125))`

When I displayed my polygon in 2d it look like 
![image](https://github.com/user-attachments/assets/9d4cd5ee-f20a-452e-9310-7a2314d99fca)

Bu when I tringulate it and displayed in 2d dimension it look like

![image](https://github.com/user-attachments/assets/8839158b-a369-4467-a366-69ace499aeac)

 I think tringles these have been created must be on the edges . Can you give me advise if I am making samething wrong or it works wrongly?
Thanks in advance

**Comment by bertt** [comment]
Hi, is it a valid polygon? ( st_isvalid). And do you use latest version?

**Comment by jacksparrow47** [comment]
Thanks bertt I hadn't checked that because it was coming from the file
