### ISSUE TITLE
vertical polygon triangulation

### ISSUE THREAD

**Issue by skemaikin** [bertt/triangulator#2]
Hi!
I noticed that you use the earcut algorithm for polygon triangulation. But it doesn't know how to work with vertical polygons. It would be very useful to be able to work with such objects. I saw a good advice on how to do this here: [github.com/mapbox/earcut/issues/21#issuecomment-98119437](https://github.com/mapbox/earcut/issues/21#issuecomment-98119437). 
This would be a very useful feature.

**Comment by bertt** [comment]
Hi, the vertical polygons are projected to 2D and back, so it should work

**Comment by skemaikin** [comment]
> Hi, the vertical polygons are projected to 2D and back, so it should work

Will the side faces of the cube be triangulated (XZ-,  YZ-planes) ?

**Comment by skemaikin** [comment]
> Hi, the vertical polygons are projected to 2D and back, so it should work

I have checked it. Everything is ok.
