### ISSUE TITLE
collinear points

### ISSUE THREAD

**Issue by skemaikin** [bertt/triangulator#4]
Hi!
There is my enhancement for the `PolygonExtensions`:

```
namespace Triangulate
{
    public static class PolygonExtensions
    {
        public static Vector3 GetNormal(this Polygon polygon)
        {
            var vect01 = polygon.ExteriorRing.Points[1].ToVector3() - polygon.ExteriorRing.Points[0].ToVector3();
            var vect02 = polygon.ExteriorRing.Points[polygon.ExteriorRing.Points.Count - 2].ToVector3() - polygon.ExteriorRing.Points[0].ToVector3();
            
            var maxProd = Vector3.Cross(vect01, vect02);
            var maxLen = maxProd.Length();
            
            for (var i = 3; i < polygon.ExteriorRing.Points.Count-1; i++)
            {
                var vect0i = polygon.ExteriorRing.Points[polygon.ExteriorRing.Points.Count - i].ToVector3() - polygon.ExteriorRing.Points[0].ToVector3();
                var vectProd = Vector3.Cross(vect01, vect0i);
                var vectLen = vectProd.Length();

                if (vectLen > maxLen) {
                    maxLen = vectLen;
                    maxProd = vectProd;
                }
            }

            return Vector3.Normalize(maxProd);
        }
    }
}
```
This allows to handle cases with collinear points on polygons.

**Comment by bertt** [comment]
Hi, can you make a pr and a unit test demonstrating this?

**Comment by skemaikin** [comment]
> Hi, can you make a pr and a unit test demonstrating this?

I don't want to make a fork (

**Comment by skemaikin** [comment]
done

**Comment by skemaikin** [comment]
Sorry, I found errors in my code. PR will come later (collinear points, duplicate points).

**Comment by bertt** [comment]
ok

**Comment by skemaikin** [comment]
Having studied the problem in detail that occurs with the data which I have, I have come to a conclusion that the calculations which are made by the `GetNormal` function have problems with the precision. The `Vector3` class from the `System.Numerics` is built on the `float` type basis, while classes from the `Wkx` library use the `double` type. As a result, when casting data to `Vector3` the precision is lost. 

I decided not to look for the libraries which would replace `System.Numerics` for using `double` type, but I just rerwrote the code in the `GetNormal` function.
It came out not entirely as it would in `C#` style, but I just left this code as is:
<details>

public static Vector3 GetNormal(this Polygon polygon)
{
    // calculating normal vector whith skipping the consecutive duplicate vertices

    double epsilon = 1e-10;
    
    double startX = (double)polygon.ExteriorRing.Points[0].X;
    double startY = (double)polygon.ExteriorRing.Points[0].Y;
    double startZ = (double)polygon.ExteriorRing.Points[0].Z;
    
    for (int i = 1; i < polygon.ExteriorRing.Points.Count-1; i++)
    {
        // find the first vector for cross product
        // skip point if it duplicates ptStart
        double v1X = (double)polygon.ExteriorRing.Points[i].X - startX;
        double v1Y = (double)polygon.ExteriorRing.Points[i].Y - startY;
        double v1Z = (double)polygon.ExteriorRing.Points[i].Z - startZ;
        
        double v1Length = Math.Sqrt(v1X*v1X + v1Y*v1Y + v1Z*v1Z);
        if (v1Length < epsilon)
            continue;

        // the first vector found
        // get the second vector and calculate cross product
        // select the best cross product: max cross product
        double maxProdLen = 0.0;
        double maxCrossProdX = 0.0;
        double maxCrossProdY = 0.0;
        double maxCrossProdZ = 0.0;

        for (int j = i+1; j < polygon.ExteriorRing.Points.Count-1; j++)
        {
            // skip point if it duplicates ptStart
            double v2X = (double)polygon.ExteriorRing.Points[j].X - startX;
            double v2Y = (double)polygon.ExteriorRing.Points[j].Y - startY;
            double v2Z = (double)polygon.ExteriorRing.Points[j].Z - startZ;

            double v2Length = Math.Sqrt(v2X*v2X + v2Y*v2Y + v2Z*v2Z);
            if (v2Length < epsilon)
                continue;

            // the second vector found
            // calculate and get the best cross product
            double crossProdX = v1Y*v2Z - v1Z*v2Y;
            double crossProdY = v1Z*v2X - v1X*v2Z;
            double crossProdZ = v1X*v2Y - v1Y*v2X;

            double prodLen = Math.Sqrt(crossProdX*crossProdX + crossProdY*crossProdY + crossProdZ*crossProdZ);
            if (prodLen > maxProdLen) {
                maxProdLen = prodLen;
                maxCrossProdX = crossProdX;
                maxCrossProdY = crossProdY;
                maxCrossProdZ = crossProdZ;
            }
        }

        if (Math.Abs(maxCrossProdX) > Math.Abs(maxCrossProdY) && Math.Abs(maxCrossProdX) > Math.Abs(maxCrossProdZ))
            // (yz) projection
            if (maxCrossProdX > 0)
                return new Vector3(1, 0, 0);
            else
                return new Vector3(-1, 0, 0);
        else if (Math.Abs(maxCrossProdY) > Math.Abs(maxCrossProdZ))
            // (zx) projection
            if (maxCrossProdY > 0)
                return new Vector3(0, 1, 0);
            else
                return new Vector3(0, -1, 0);
        else
            // (xy) projection
            if (maxCrossProdZ > 0)
                return new Vector3(0, 0, 1);
            else
                return new Vector3(0, 0, -1);
    }

    return new Vector3(0, 0, 0);
}
</details>

This code has helped me to solve the problems with the small-sized polygons as well as with duplicate vertecies. 

I'll try to select and send some of the polygons which demonstrate these problems. I won’t do PR until I have processed a large amount of data and compared the results. On the other hand, perhaps you will find a more elegant solution.

**Comment by bertt** [comment]
ok, if I understand correctly you are trying to solve two issues:

- duplicate vertices -> currently not handled?

- small polygons -> currently handled by the epsilon parameter

And not some (which?) issue with collinear points.

About the accuracy: keep in mind in practice this library is used in programs where the distance unit is meters relative to a center point (and not decimal degrees like in the unit test). For example epsg:4978 coordinates relative to the center point of the area of interest. When using relative meters there will be less issues with duplicate vertices, float/double precision and small triangles. 

About the normals calculation: I'm thinking to improve the algorithm by calculating a normal per vertice (based on neighbour vertices) and averaging to give 'the' normal of the polygon.

So far I've used this library without (obvious) errors, but if you encounter a case that needs a fix let me know.

**Comment by skemaikin** [comment]
Yes, I have two problems. 
1: the data - not all polygons are correct (duplicate vertices, degenerated shapes). This problem can be solved by cleaning geometries and correct enumerating vertices.
2: calculation precision. It seems to me that there is such a problem. Look at the attached screens:
![image](https://github.com/bertt/triangulator/assets/62253043/240653b7-973a-4d5f-be35-aba0d8766d57)
Left screen: Point(double) -> Vector3(float)
Right screen: calculation with double.
All data are in lat/lon.

**Comment by bertt** [comment]
nice images! is this in mapbox? 
Anyway, if you're after high precision better not to use lat/lon (but some other/local projection), or have a library that uses doubles not floats. In my cases I always do the first.

**Comment by skemaikin** [comment]
> nice images! is this in mapbox? Anyway, if you're after high precision better not to use lat/lon (but some other/local projection), or have a library that uses doubles not floats. In my cases I always do the first.

This is deck.gl. Now solution stack is: shp (4326) -> tesselate_building -> pg2b3dm -> deck.gl.

**Comment by bertt** [comment]
There is pg2b3dm 2.5.0 with this new triangulation method
